server:
  port: 8082
spring:
  banner:
    location: banner.txt
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=maab
    driver-class-name: org.postgresql.Driver
    username: postgres
    password:

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: true

springdoc:
  swagger-ui:
    path: /swagger-ui
    operations-sorter: method
  api-docs:
    path: /api/docs